name: Check binary size

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled, ready_for_review]

jobs:
  check_size:
    runs-on: ubuntu-latest
    # Check if pull request does not have label "bloat-ok".
    if: "!contains(github.event.pull_request.labels.*.name, 'bloat-ok')"
    steps:
    - uses: actions/checkout@v3
      with:
        # Needed to rebase against the base branch
        fetch-depth: 0
    - name: Configure git user details
      run: |
        git config --global user.email "bloatchecker@example.com"
        git config --global user.name "Bloat Checker"
    - name: Configure base branch without switching current branch
      run: git fetch origin ${GITHUB_BASE_REF}:${GITHUB_BASE_REF}
    - name: Compare binary size change across each commit
      run: git rebase -v ${GITHUB_BASE_REF}^ -x test/check-size.sh
