name: Run coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          # needed for codecov
          fetch-depth: 0
      - name: Install tools
        run: sudo apt-get install -qqy bats
      - name: Run make coverage
        run: make coverage
      - name: Run make codecov
        run: make codecov
