name: Run coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        run: sudo apt-get install -qqy bats
      - name: Run make coverage
        run: make coverage
      - name: Run make codecov
        run: make codecov
