name: markdown-lint

on:
  push:
    paths:
      - README.md
  pull_request:
    paths:
      - README.md
jobs:
  lint_markdown:
    name: Run markdown linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint markdown
      uses: DavidAnson/markdownlint-cli2-action@v9
      with:
        globs: |
          README.md
