name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        run: sudo apt-get install -qqy shellcheck bats
      - name: Run make shellcheck
        run: make shellcheck
      - name: Run make all
        run: make all
      - name: Run make test
        run: make test
      - name: Run make install/uninstall
        run: test/uninstall.sh

